import Head from "next/head";
import { LoginForm } from "../features/login/components/LoginForm";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login with Context - Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Login with Context - Example</h1>
        <LoginForm />
        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
